### PR TITLE
feat: add container and publish it to GHCR

### PR DESCRIPTION
**Pull request by onedr0p**
👋🏼 @blacktwin 

I have created a `Dockerfile` and a GH workflow to build and push the container to your packages. I have had this working for awhile and build my own image but if you aren't too keen on supporting this I understand.

## Usage

I created a helper bash script so people can set the `JBOPS_SCRIPT_PATH` to the script they want to run (e.g. `JBOPS_SCRIPT_PATH=fun/plexapi_haiku.py` and any args for the script are passed to the python script. For a complete example, check out this docker compose with [ofelia](https://github.com/mcuadros/ofelia):

```yaml
services:
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - jbops-offdeck
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  jbops-offdeck:
    image: ghcr.io/blacktwin/jbops:latest
    container_name: jbops-offdeck
    user: 1000:1000
    volumes:
      - ./config.ini:/config/config.ini:ro
    environment:
      - JBOPS_SCRIPT_PATH=utility/off_deck.py
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.jbops-offdeck.schedule: "@every 10m"
      ofelia.job-exec.jbops-offdeck.command: "/docker-entrypoint.sh --playlists SleepMix"
```

## Limitations

Currently the `maps/requirements.txt` will not build. I tried with Python 3.10, 3.11 and 3.12 but it won't build `pyproj` with the below error so I omitted it for now. Not sure why this is happening but if you have any pointers I am all ears.

```
#8 223.6 Collecting pyproj<3.7.0,>=1.9.3
#8 223.6   Downloading pyproj-3.6.1.tar.gz (225 kB)
#8 223.6      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.1/225.1 kB 33.6 MB/s eta 0:00:00
#8 223.7   Installing build dependencies: started
#8 225.2   Installing build dependencies: finished with status 'done'
#8 225.2   Getting requirements to build wheel: started
#8 225.3   Getting requirements to build wheel: finished with status 'error'
#8 225.3   error: subprocess-exited-with-error
#8 225.3   
#8 225.3   × Getting requirements to build wheel did not run successfully.
#8 225.3   │ exit code: 1
#8 225.3   ╰─> [1 lines of output]
#8 225.3       proj executable not found. Please set the PROJ_DIR variable. For more information see: https://pyproj4.github.io/pyproj/stable/installation.html
#8 225.3       [end of output]
#8 225.3   
#8 225.3   note: This error originates from a subprocess, and is likely not a problem with pip.
#8 225.3 error: subprocess-exited-with-error
#8 225.3 
#8 225.3 × Getting requirements to build wheel did not run successfully.
#8 225.3 │ exit code: 1
#8 225.3 ╰─> See above for output.
#8 225.3 
#8 225.3 note: This error originates from a subprocess, and is likely not a problem with pip.
```

Hope this finds you well, happy holidays!

### CODE REVIEW

**Comment by strenkml** [comment]
The requirements.txt file doesn't include all of the dependencies that are required for all of the scripts. I used pipreqs to generate this requirements.txt file:
```
flatten_json==0.1.14
future==0.18.3
gmusicapi==13.0.0
google_api_python_client==2.113.0
httplib2==0.22.0
matplotlib==3.8.2
oauth2client==4.1.3
Pillow==10.2.0
plexapi==4.15.7
psutil==5.9.7
python_twitter==3.5
Requests==2.31.0
urllib3==2.1.0
```

**Comment by onedr0p** [comment]
Thanks! I'll test this locally and push the change to the PR if there's no issues.

**Comment by blacktwin** [comment]
I'm not sure how to actually use/test this and given that it's taken me months to even comment on this issue, no I'm not very keen to support this 🥲. Sorry.

**Comment by onedr0p** [comment]
No problem, thanks anyways!

**Pull request closed without merging**
