### PR TITLE
Added: Concurrent streams by user

### PR DESCRIPTION
**Pull request by WikiZell**
Added functions: streamAllowed and configUser

Usage:

From the terminal:

Create the configuration file with the command:
python3 kill_stream.py --jbop configUser

A file "userConfig.ini" will be created in the script folder.

Exemple of userConfig.ini :

[18422708]
friendly_name = John Doe
user_id = 18422708
user_slot = 1 ; Maximum number of streams allowed for the selected user. Default value is 1

In Tautulli:

Notification Agents -> Script -> [Triggers -> Playback Start]
[Arguments -> Playback Start]:

--jbop streamAllowed --username {username} --sessionId {session_id} --streamCount {user_streams} --userId {user_id}

***
Config file is automatically synced with Tautulli database.
Users are added and removed according to Tautulli users list.

### CODE REVIEW

**Comment by samwiseg00** [comment]
Can't this already be accomplished today with a custom conditions? The trigger would be playback start. You can even put more than one `User Streams` in a single notifier... 

Single:


multiple:

**Comment by WikiZell** [comment]
Yes, at the begin i was using the script in the way you explained, But when you have lot of users on the server  its getting a little bit unhandy to manage and update . I wanted something that by default set the stream to 1  for each user (present and future) and also if i remove the user from the server i dont want to care about update the condition/logic script.
And  i am using the ini file not just to control concurrent streams only but also also to manage  subscriptions DATE. On my github there is the script.

**Comment by samwiseg00** [comment]
You can make a default rule that would include all users. Current and future. 

This example shows you how you can exclude a specific user if needed.

**Comment by blacktwin** [comment]
@WikiZell I'd prefer to keep this script stream focused and driven by Tautulli's conditions and arguments.

**Pull request closed without merging**
