### PR TITLE
Fix for crash when lat/long are N/A

### PR DESCRIPTION
**Pull request by Collisionc**
Just checks for N/A before trying to do anything with the data, then skips if necessary.

### CODE REVIEW

**Comment by blacktwin** [comment]
Thanks but that wouldn't solve the problem when creating a geojson. There are several reasons why a N/A value could be present. If the IP is local for instance. The check should probably be closer to capture and provide an err out to show which data point is the culprit.

**Comment by blacktwin** [comment]
Passing on errors in get_geoip_info function instead of [returning it](https://github.com/blacktwin/JBOPS/blob/master/maps/ips_to_maps.py#L151).

Changing the [get_geo_dict function's exception](https://github.com/blacktwin/JBOPS/blob/master/maps/ips_to_maps.py#L195-L198) to catch and return culprit.

```python
    except AttributeError:
        print('User: {} IP: {} caused error in geo_dict.'.format(a.friendly_name, a.ip_address))
        pass
    except Exception as e:
        print(e)
        pass
    return geo_dict
```

**Comment by blacktwin** [comment]
@Collisionc can you please confirm this update works for you?

**Comment by Collisionc** [comment]
Works great, thanks!

**Pull request closed without merging**
