### PR TITLE
Update hide_episode_spoilers to change all shows. 

### PR DESCRIPTION
**Pull request by aldoblack**
`--rating_key` is optional now. If it's not defined, the script will update all shows.

### CODE REVIEW

**Comment by blacktwin** [comment]
> If it's not defined, the script will update all shows.

You don't see a problem with that?

**Comment by aldoblack** [comment]
> You don't see a problem with that?

I'm sorry. I did not understand your reply. Where might be the problem?

**Comment by blacktwin** [comment]
Sorry for the hot response with no immediate follow up. The issue I see is that the simple mistake of not using the `--rating_key` arg would have a very big impact on someone's server. I don't think something so simple as missing an arg should trigger such a large change to an environment. I can see utilizing this edit or a form of it for a 1 time run then lean on Tautulli to slip the poster back. However the intend of this script is to be used with Tautulli and have Tautulli manage what is hidden and then what is revealed. 

I don't want to include a change that would allow for such a big change in someone's server.

**Comment by blacktwin** [comment]
Please see the example in #317

**Pull request closed without merging**
